# Copyright 2020 Intel Corporation
# SPDX-License-Identifier: Apache 2.0

FROM ubuntu:20.04
RUN apt-get update && apt-get install -y openjdk-11-jdk
RUN apt-get install -y wget

# Create a user 'sdouser'. If the user name is updated, please update the same
# in cmdDocker.sh.

RUN useradd -ms /bin/bash sdouser
USER sdouser
WORKDIR /home/sdouser/
RUN mkdir ./certs

# Copy dependencies to container

COPY *.war /home/sdouser
COPY cmdDocker.sh /home/sdouser
COPY certs/ /home/sdouser/certs

# Start service

EXPOSE 8000
ENTRYPOINT ["sh", "cmdDocker.sh"]

# Docker image healthcheck

HEALTHCHECK --interval=30s --timeout=30s CMD wget --spider -Y off http://localhost:8001/mp/113/health || exit 1 
